In [2]:
# Linear Binary Classification
# Given a set of N points in the D-dimensional space and their labels of boolean values, find a hyperplane that separates the true and false class. Return a classifier that takes in a point vector and returns probility.

import numpy as np

def binary_classifier_from(X, Y):
    '''
        X, a float np.array of shape [N, D]
        Y, a boolean array of labels, shape [N]
    '''
    epsilon = 1e-5

    D = X.shape[1]

    np.random.seed(42)
    W = np.random.randn(D)  # D,
    b = 0  # 1

    lr = 0.001

    def sigmoid(x):
        return (1 + np.exp(-x)) ** -1
    def d_sigmoid(x):
        # -1 * (1 + np.exp(-x)) ** -2 * np.exp(-x) * -1
        # return sigmoid(x) ** 2 * np.exp(-x)  
        return  sigmoid(x) * (1 -  sigmoid(x))
    
    m = X.mean(0)
    std = X.std()

    def forward(vectors):
        standardized_v = (vectors - m) / (std + epsilon)
        logit = standardized_v @ W + b  # N
        prob = sigmoid(logit)  # N
        return prob

    for i in range(200):
        # Forward
        prob = forward(X)  # N
        labels = Y * 1.0
        loss = - labels * np.log(prob + epsilon) - (1 - labels) * np.log(1 - prob + epsilon)

        # Backward
        standardized_x = (X - m) / (std + epsilon)
        # d_prob = - labels / (prob + epsilon) + (1 - labels) / (1 - prob + epsilon)  # N
        # d_logit = prob * (1 - prob) * d_prob # N
        d_logit = prob - labels
        d_W = standardized_x.T @ d_logit  # D
        d_b = d_logit.sum()

        W -= lr * d_W
        b -= lr * d_b

        print(f"loss.mean={loss.mean()}")
        # break

    return forward


# train_data = np.array([
#     [0, 1], [1, 2], [3, 4], [1, 1], [2, 3],
# ], dtype=float)
# train_labels = np.array([True, True, True, False, True])

# train_data = np.array([
#     [0, 1], [1, 2],
# ], dtype=float)
# train_labels = np.array([True, False])

train_data = np.concatenate(
    [
        np.random.randn(100, 10) + np.array([50, 20] + [0] * 8, dtype=float),
        np.random.randn(100, 10) + np.array([20, 0] + [0] * 8, dtype=float),
    ], axis=0)
train_labels = np.array([True] * 100 + [False] * 100)

model = binary_classifier_from(train_data, train_labels)
print(model(train_data))

loss.mean=0.4791393152765643
loss.mean=0.41838117379848255
loss.mean=0.369285921512877
loss.mean=0.3291588509102313
loss.mean=0.2959808169654386
loss.mean=0.26824010047622726
loss.mean=0.2447996430785635
loss.mean=0.22479755231432375
loss.mean=0.20757435199533358
loss.mean=0.19262030681387834
loss.mean=0.17953733421769708
loss.mean=0.168011366352509
loss.mean=0.15779216630407647
loss.mean=0.14867846961230213
loss.mean=0.1405069487524031
loss.mean=0.13314394104834334
loss.mean=0.1264791901999657
loss.mean=0.12042106771970801
loss.mean=0.1148928916741768
loss.mean=0.10983006626290144
loss.mean=0.10517784079121043
loss.mean=0.10088954001269132
loss.mean=0.09692515614889809
loss.mean=0.093250220622694
loss.mean=0.08983489376341539
loss.mean=0.086653225608543
loss.mean=0.08368255194290793
loss.mean=0.08090299794309395
loss.mean=0.07829706798435392
loss.mean=0.0758493048583452
loss.mean=0.0735460052301705
loss.mean=0.07137498091413487
loss.mean=0.06932535767514425
loss.mean=0.067387404918360

With 
        d_prob = - labels / (prob + epsilon) + (1 - labels) / (1 - prob + epsilon)  # N
        d_logit = prob * (1 - prob) * d_prob # N
in the backprob, it's very same:

loss.mean=0.47989471852639026
loss.mean=0.4190224805366235
loss.mean=0.3698198680071503
loss.mean=0.32959864629758917
loss.mean=0.2963408932624755
loss.mean=0.26853386425829784
loss.mean=0.24503870297758878
loss.mean=0.22499161669233395
loss.mean=0.20773139806909896
loss.mean=0.1927468346361424
loss.mean=0.17963862408216955
loss.mean=0.16809170825330783
loss.mean=0.1578550528428587
loss.mean=0.14872675337547514

In [10]:
# multi-class logistic regression

# loss = numpy.F.cross_entropy(logits, Y)
# what is d_logits?

# probs = softmax(logits)
# loss = -np.log(probs[y]).mean()

# loss = - log(e ** logits[y] / SUM_j(e ** logits[j]) )

# dL / d(logits[i]) = - probs[y] ** -1 * d (e ** logits[y] / SUM_j(e ** logits[j]) / d(logits[i])
# if i != y
#  dL / d(logits[i]) = - probs[y] ** -1  * (-1) e ** logits[y] / SUM_j(e ** logits[j]) ** 2 * e ** logits[i]
#  dL / d(logits[i]) = - probs[y] ** -1  * (-1) prob[y] * prob[i]
#  dL / d(logits[i]) = prob[i]
# if i == y
#  dL / d(logits[i]) = - probs[y] ** -1 * 
#      (e ** logits[i] * SUM_j(e ** logits[j]) - d(SUM_j(e ** logits[j]))/dlogit[i] * e ** logits[i])
#      / SUM_j(e ** logits[j]) ** 2
#  dL / d(logits[i]) = - probs[y] ** -1 *
#      (e ** logits[i] * SUM_j(e ** logits[j]) - e ** logits[i] * e ** logits[i])
#      / SUM_j(e ** logits[j]) ** 2
#  dL / d(logits[i]) = - probs[y] ** -1 * e ** logits[i] *(SUM_j(e ** logits[j]) -  e ** logits[i])
#      / SUM_j(e ** logits[j]) ** 2
#  dL / d(logits[i]) = - probs[y] ** -1 * prob[i] *(1 -  e ** logits[i] / SUM_j(e ** logits[j]) )
#  dL / d(logits[i]) = - (1 - prob[i])
#  dL / d(logits[i]) = prob[i] - 1

def softmax(x, dim):
  x_maxes = np.max(x, dim, keepdims=True)
  norm_x = x - x_maxes # subtract max for numerical stability
  counts = np.exp(norm_x)
  counts_sum = counts.sum(dim, keepdims=True)
  counts_sum_inv = counts_sum**-1
  return counts * counts_sum_inv  # B, V

def grad_of_loss_wrt_logits(logits, Y):
  d_logits = softmax(logits, 1)
  d_logits[range(logits.shape[0]), Y] -= 1.0
  return d_logits / logits.shape[0]

# softmax(np.zeros([2, 2], dtype=float), 1)

test_logits = np.array(
  [
    [0.4, 0.0, -4.0, -1.0],
    [0.4, 0.0, -4.0, -10.0],
  ],
  dtype=float,
)
# test_logits.shape
test_Y = np.array([1, 3], dtype=int)

logits_grad = grad_of_loss_wrt_logits(test_logits, test_Y)
print(f"test_logits={test_logits}")
print(f"softmax(test_logits)={softmax(test_logits, 1)}")
print(f"logits_grad={logits_grad}")

# verify by numerical gradient
epsilon = 0.0001
test_logits_w_d = test_logits.copy()
test_logits_w_d[1, 1] += epsilon
print(f"test_logits_w_d={test_logits_w_d}")

def cross_entropy_loss(logits, labels):
  '''
    prob: dtype float, shape of [B, C], the probability of each class
    labels: dtype int, shape of [B, 1], the class label indices
  '''
  prob = softmax(logits, 1)
  return -np.log(prob)[range(logits.shape[0]), labels].mean()

(cross_entropy_loss(test_logits_w_d, test_Y) - cross_entropy_loss(test_logits, test_Y)) / epsilon

test_logits=[[  0.4   0.   -4.   -1. ]
 [  0.4   0.   -4.  -10. ]]
softmax(test_logits)=[[5.18351093e-01 3.47461129e-01 6.36397256e-03 1.27823806e-01]
 [5.94308491e-01 3.98376895e-01 7.29652735e-03 1.80862831e-05]]
logits_grad=[[ 0.25917555 -0.32626944  0.00318199  0.0639119 ]
 [ 0.29715425  0.19918845  0.00364826 -0.49999096]]
test_logits_w_d=[[ 4.e-01  0.e+00 -4.e+00 -1.e+00]
 [ 4.e-01  1.e-04 -4.e+00 -1.e+01]]


0.1991944394497125